import { __ } from '@wordpress/i18n';

export const pricingUrl = window.bp3dBlock?.admin_url + 'edit.php?post_type=bp3d-model-viewer&page=3d-viewer#/pricing'

export const helpText: Record<string, string> = {
    viewerType: __('Choose between Lite and Advanced viewer modes. Lite is optimized for GLB and GLTF files with strong performance and essential features. Advanced supports almost all 3D file types but offers a more streamlined feature set.', '3d-viewer'),
    modelUrl: __('Specifies the URL of the 3D model file to be displayed in the viewer.', '3d-viewer'),
    modelPoster: __('Sets a placeholder image that is shown before the 3D model finishes loading.', '3d-viewer'),
    useMultiple: __('Enables multiple models in a single viewer, allowing users to switch between different 3D models.', '3d-viewer'),
    skyboxImage: __('Sets a skybox image that appears as the background and provides environmental lighting for the model.', '3d-viewer'),
    skyboxHeight: __('Controls the vertical height of the skybox environment. Adjust this to better align the background and lighting with your model.', '3d-viewer'),
    useDecoder: __('Selects which decoder to use for loading the model. Choose Draco if your model is compressed, or None for standard models.', '3d-viewer'),
    initialView: __('Defines the initial camera angle and orientation of the model when the viewer first loads.', '3d-viewer'),
    rotate: __('Allows users to manually rotate the 3D model using mouse or touch gestures.', '3d-viewer'),
    autoRotate: __('Automatically rotates the 3D model without user interaction. Great for showcasing products.', '3d-viewer'),
    autoRotationDelay: __('Sets the delay time before automatic rotation starts after the model loads or after user interaction stops.', '3d-viewer'),
    rotationPerSecond: __('Controls how fast the model rotates automatically. Higher values mean faster rotation.', '3d-viewer'),
    autoplay: __('Automatically starts model animation when the viewer loads.', '3d-viewer'),
    zoom: __('Enables zooming in and out of the 3D model using mouse scroll or touch gestures.', '3d-viewer'),
    zoomLevel: __('Sets the default zoom level of the model. Higher values zoom in closer.', '3d-viewer'),
    zoomInOutBtn: __('Displays zoom in and zoom out buttons on the viewer interface.', '3d-viewer'),
    mouseControl: __('Allows users to rotate, pan, and interact with the model using a mouse or touch input.', '3d-viewer'),
    fullscreen: __('Shows a fullscreen button so users can view the model in fullscreen mode.', '3d-viewer'),
    cameraBtn: __('Displays a camera button that lets users capture the current view of the model.', '3d-viewer'),
    isNavigation: __('Shows navigation controls for switching between multiple models.', '3d-viewer'),
    isPagination: __('Displays pagination dots or thumbnails when multiple models are available.', '3d-viewer'),
    variant: __('Enables model variants if your 3D file supports multiple variations.', '3d-viewer'),
    shadow: __('Adds realistic shadows beneath the model to improve depth and realism.', '3d-viewer'),
    shadowIntensity: __("Controls how dark or light the model's shadow appears. Higher values create darker, more visible shadows.", '3d-viewer'),
    exposure: __('Adjusts the brightness of the model scene. Higher values make the model brighter.', '3d-viewer'),
    tonMapping: __("Controls how colors and brightness are mapped for rendering. Use 'neutral' for balanced output, or try other modes for different looks.", '3d-viewer'),
    arEnabled: __('Enables AR (Augmented Reality) so visitors can view the 3D model in their real environment on supported devices.', '3d-viewer'),
    modeliSOSrc: __('Specifies the iOS-specific model file (.usdz) used for viewing the 3D model in AR on Apple devices.', '3d-viewer'),
    arPlacement: __("Defines how the model is placed in AR. Choose 'floor' to place the model on the ground or 'wall' to attach it to a vertical surface.", '3d-viewer'),
    arMode: __("Selects the AR viewing mode. 'Quick Look' is used for iOS devices, while other modes enable AR on supported Android devices.", '3d-viewer'),
    environmentImage: __('Sets an environment image to improve lighting and reflections on the model.', '3d-viewer'),
    useEnvironmentAsSkybox: __('Uses the environment image as the background skybox instead of a solid color.', '3d-viewer'),
    loadingPercentage: __('Shows the loading percentage while the 3D model is being loaded.', '3d-viewer'),
    progressBar: __('Displays a progress bar during model loading to indicate loading status.', '3d-viewer'),
    lazyLoad: __('Delays loading the 3D model until it becomes visible on the screen, improving performance.', '3d-viewer'),
    preload: __('Controls how the model is preloaded. Auto lets the browser decide the best loading strategy.', '3d-viewer'),
    rotateAlongX: __('Sets the initial rotation angle of the model along the X axis.', '3d-viewer'),
    rotateAlongY: __('Sets the initial rotation angle of the model along the Y axis.', '3d-viewer'),
    lockXAxisRotation: __('Prevents the model from rotating along the X axis.', '3d-viewer'),
    lockYAxisRotation: __('Prevents the model from rotating along the Y axis.', '3d-viewer'),
    animationSelector: __('Enables animation selector if the model contains animations.', '3d-viewer'),
    selectedAnimation: __('Selects which animation to play from the available animations in the model.', '3d-viewer'),
    hotspots: __('Adds interactive hotspots to the model for displaying information or actions.', '3d-viewer'),
    hotspotStyle: __('Chooses the visual style for hotspots displayed on the model.', '3d-viewer'),
    placement: __('Defines how the viewer is placed in the layout, such as block or inline.', '3d-viewer'),
    texturePanel: __('Allows you to apply and customize textures on supported 3D models. This feature is experimental and may vary depending on the model.', '3d-viewer'),
    selectedMaterial: __('Selects the material from the 3D model where textures and properties will be applied.', '3d-viewer'),
    baseColor: __('Controls the base color of the selected material. You can adjust the color factor or apply a texture image.', '3d-viewer'),
    baseColorFactor: __('Adjusts the base color intensity of the material. This color blends with the applied texture.', '3d-viewer'),
    availableTextures: __('Shows textures already available for the the model.', '3d-viewer'),
    uploadTexture: __('Uploads a new texture image to apply to the selected material.', '3d-viewer'),
    metallicRoughness: __('Controls how metallic and rough the surface of the material appears.', '3d-viewer'),
    metallicFactor: __('Adjusts how metallic the material looks. Higher values create a more metal-like surface.', '3d-viewer'),
    roughnessFactor: __('Adjusts how rough or smooth the surface appears. Lower values make the surface shinier.', '3d-viewer'),
    resetTexture: __('Resets the applied texture or factor back to its default value.', '3d-viewer'),
    width: __('Sets the width of the 3D viewer. You can use values like %, px, or vw for responsive layouts.', '3d-viewer'),
    height: __('Sets the height of the 3D viewer. Adjust this to control how much vertical space the model occupies.', '3d-viewer'),
    modelBG: __('Sets the background color of the 3D viewer. Use transparent or any valid CSS color value.', '3d-viewer'),
    progressbarColor: __('Changes the color of the loading progress bar shown while the model is loading.', '3d-viewer'),
    align: __('Controls the alignment of the 3D viewer within its container, such as left, center, or right.', '3d-viewer'),
    customCSS: __('Add your own CSS to style the 3D viewer. Use this to customize spacing, colors, buttons, or other UI elements.', '3d-viewer'),
    additionalID: __('Adds a custom HTML ID to the 3D viewer wrapper. Useful for targeting the viewer with CSS or JavaScript.', '3d-viewer'),
    additionalClass: __('Adds custom CSS class names to the 3D viewer wrapper for advanced styling or scripting.', '3d-viewer'),
};
